######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 26 16:06:35 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += martello.h
SOURCES += main.cpp
